# Generated by Django 4.0.3 on 2022-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
