# Generated by Django 4.0.3 on 2022-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_medicine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='requested_stock',
            field=models.IntegerField(null=True),
        ),
    ]
