# Generated by Django 4.0.3 on 2022-03-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='medicine_id',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
    ]
