# Generated by Django 4.0.3 on 2022-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_medicine_id_purchase_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
