# Generated by Django 4.0.3 on 2022-03-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_purchase_requested_med_purchase_verify_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
