# Generated by Django 4.0.3 on 2022-03-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_purchase_is_purchced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='verify_med',
        ),
    ]
