# Generated by Django 4.0.3 on 2022-03-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_purchase_verify_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='sell',
            field=models.IntegerField(default=0),
        ),
    ]
