# Generated by Django 4.0.3 on 2022-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_medicine_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
