# Generated by Django 4.0 on 2022-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_medicine_photo_link_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_cart',
            field=models.BooleanField(default=False),
        ),
    ]
