# Generated by Django 4.0 on 2022-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='requested_med',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_requested_med',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='cart', max_length=20),
        ),
    ]
