# Generated by Django 4.0 on 2022-04-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_purchase_requested_med_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='is_requested_med',
            new_name='is_requested',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Cart', max_length=20),
        ),
    ]
