# Generated by Django 4.0 on 2022-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_purchase_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_clear_byUser',
            field=models.BooleanField(default=False),
        ),
    ]
